config/routes.rb
Rails.application.routes.draw do

  resources :events

  resources :musics

  resources :photos

  get 'welcome/aboutus'

  get 'welcome/contactus'

 

  resources :tasks 

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/music.rb
class Music < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

layout "events"
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:january, :february, :march, :april, :may, :june, :july, :august, :september, :october, :november, :december)
    end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController

  
  before_action :set_music, only: [:show, :edit, :update, :destroy]

  layout "musics"
  
  def index
    @musics = Music.all
  end

  # GET /musics/1
  # GET /musics/1.json
  def show
  end

  # GET /musics/new
  def new
    @music = Music.new
  end

  # GET /musics/1/edit
  def edit
  end

  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(music_params)

    respond_to do |format|
      if @music.save
        format.html { redirect_to @music, notice: 'Music was successfully created.' }
        format.json { render :show, status: :created, location: @music }
      else
        format.html { render :new }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musics/1
  # PATCH/PUT /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to @music, notice: 'Music was successfully updated.' }
        format.json { render :show, status: :ok, location: @music }
      else
        format.html { render :edit }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url, notice: 'Music was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def music_params
      params.require(:music).permit(:title)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

 layout "photos"

  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:Blanca, :concerts, :fans)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :status)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
layout "contact"
 # GET /contact
  # GET /contact.json
  def aboutus
  end

  def contactus
  end

  def music
  end

  def photos
  end

  def events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :january %><br>
    <%= f.text_field :january %>
  </div>
  <div class="field">
    <%= f.label :february %><br>
    <%= f.text_field :february %>
  </div>
  <div class="field">
    <%= f.label :march %><br>
    <%= f.text_field :march %>
  </div>
  <div class="field">
    <%= f.label :april %><br>
    <%= f.text_field :april %>
  </div>
  <div class="field">
    <%= f.label :may %><br>
    <%= f.text_field :may %>
  </div>
  <div class="field">
    <%= f.label :june %><br>
    <%= f.text_field :june %>
  </div>
  <div class="field">
    <%= f.label :july %><br>
    <%= f.text_field :july %>
  </div>
  <div class="field">
    <%= f.label :august %><br>
    <%= f.text_field :august %>
  </div>
  <div class="field">
    <%= f.label :september %><br>
    <%= f.text_field :september %>
  </div>
  <div class="field">
    <%= f.label :october %><br>
    <%= f.text_field :october %>
  </div>
  <div class="field">
    <%= f.label :november %><br>
    <%= f.text_field :november %>
  </div>
  <div class="field">
    <%= f.label :december %><br>
    <%= f.text_field :december %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Lista de eventos</h1>

<table>
  <thead>
    <tr>
      <th>J</th>
      <th>F</th>
      <th>M</th>
      <th>A</th>
      <th>M</th>
      <th>J</th>
      <th>J</th>
      <th>A</th>
      <th>S</th>
      <th>O</th>
      <th>N</th>
      <th>D</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.january %></td>
        <td><%= event.february %></td>
        <td><%= event.march %></td>
        <td><%= event.april %></td>
        <td><%= event.may %></td>
        <td><%= event.june %></td>
        <td><%= event.july %></td>
        <td><%= event.august %></td>
        <td><%= event.september %></td>
        <td><%= event.october %></td>
        <td><%= event.november %></td>
        <td><%= event.december %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>January:</strong>
  <%= @event.january %>
</p>

<p>
  <strong>February:</strong>
  <%= @event.february %>
</p>

<p>
  <strong>March:</strong>
  <%= @event.march %>
</p>

<p>
  <strong>April:</strong>
  <%= @event.april %>
</p>

<p>
  <strong>May:</strong>
  <%= @event.may %>
</p>

<p>
  <strong>June:</strong>
  <%= @event.june %>
</p>

<p>
  <strong>July:</strong>
  <%= @event.july %>
</p>

<p>
  <strong>August:</strong>
  <%= @event.august %>
</p>

<p>
  <strong>September:</strong>
  <%= @event.september %>
</p>

<p>
  <strong>October:</strong>
  <%= @event.october %>
</p>

<p>
  <strong>November:</strong>
  <%= @event.november %>
</p>

<p>
  <strong>December:</strong>
  <%= @event.december %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_footer_contact.html.erb
      <footer class="row">
        <div class="large-12 columns">
          <hr/>
          <div class="row">
            <div class="large-6 columns">
              <p>© Copyright no one at all. Go to town.</p>
            </div>
            <div class="large-6 columns">
              <ul class="inline-list right">
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Youtube</a></li>
                <li><a href="#">Instagram</a></li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
     

app/views/layouts/_nav_contact.html.erb
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
           
          <li class="name">
            <h1>
              <a href="#">
                Blanca Martínez
              </a>
            </h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
        </ul>
     
        <section class="top-bar-section">
           
          <ul class="right">
            <li class="divider"></li>
            <li class="has-dropdown">
              <a href="#">Eventos</a>
              <ul class="dropdown">
                <li><label>Section Name</label></li>
                <li class="has-dropdown">
                  <a href="#" class="">Has Dropdown, Level 1</a>
                  <ul class="dropdown">
                    <li><a href="#">Dropdown Options</a></li>
                    <li><a href="#">Dropdown Options</a></li>
                    <li><a href="#">Level 2</a></li>
                    <li><a href="#">Subdropdown Option</a></li>
                    <li><a href="#">Subdropdown Option</a></li>
                    <li><a href="#">Subdropdown Option</a></li>
                  </ul>
                </li>
                <li><a href="#">Dropdown Option</a></li>
                <li><a href="#">Dropdown Option</a></li>
                <li class="divider"></li>
                <li><label>Section Name</label></li>
                <li><a href="#">Dropdown Option</a></li>
                <li><a href="#">Dropdown Option</a></li>
                <li><a href="#">Dropdown Option</a></li>
                <li class="divider"></li>
                <li><a href="#">See all →</a></li>
              </ul>
            </li>
            <li class="divider"></li>
            <li><a href="#">Photos</a></li>
            <li class="divider"></li>
            <li class="has-dropdown">
              <a href="#">Music</a>
              <ul class="dropdown">
                <li><a href="#">Dropdown Option</a></li>
                <li><a href="#">Dropdown Option</a></li>
                <li><a href="#">Dropdown Option</a></li>
                <li class="divider"></li>
                <li><a href="#">See all →</a></li>
              </ul>
            </li>
          </ul>
        </section>
      </nav>
     
       
     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <meta name="viewport" content="width=device-width, initial-scale=1.0" />
 <title>Todo</title>
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'vendor/modernizr', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/contact.html.erb
<!DOCTYPE html>
<html>
<head>
 <meta name="viewport" content="width=device-width, initial-scale=1.0" />
 <title>Todo</title>
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'vendor/modernizr', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

<%= render 'layouts/nav_contact'%>
     
       
     
      <div class="row">
     
         
        <div class="large-9 columns">
     
          <h3>¡Contacta con nosotros!</h3>
          <p>Nos encantaría saber de ti. Puedes contactar con todo nuestro equipo y alguno de nuestros miembros te contestará.</p>
     
          <div class="section-container tabs" data-section>
            <section class="section">
              <h5 class="title"><a href="#panel1">Contacta con nosotros</a></h5>
              <div class="content" data-slug="panel1">
                <form>
                  <div class="row collapse">
                    <div class="large-2 columns">
                      <label class="inline">Tu nombre</label>
                    </div>
                    <div class="large-10 columns">
                      <input type="text" id="yourName" placeholder="Ana Espinar">
                    </div>
                  </div>
                  <div class="row collapse">
                    <div class="large-2 columns">
                      <label class="inline"> Tu email</label>
                    </div>
                    <div class="large-10 columns">
                      <input type="text" id="yourEmail" placeholder="anaesru@hotmail.com">
                    </div>
                  </div>
                  <label>¿Qué ocurre?</label>
                  <textarea rows="4"></textarea>
                  <button type="submit" class="radius button">Submit</button>
                </form>
              </div>
            </section>
            <section class="section">
              <h5 class="title"><a href="#panel2">Specific Person</a></h5>
              <div class="content" data-slug="panel2">
                <ul class="large-block-grid-5">
                  <li><a href="/cdn-cgi/l/email-protection#deb3bfb29eadbbacbbb0b7aaa7f0bcbdf0acbbbc"><img src="http://scontent-a.cdninstagram.com/hphotos-xpa1/t51.2885-15/1168753_365533883604424_525954342_a.jpg">Blanca Martinez</a></li>
                  <li><a href="/cdn-cgi/l/email-protection#403a2f2500332532252e2934396e22236e322522"><img src="https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/3/005/099/3b9/3e8a5f1.jpg">Carlos Martin</a></li>
                  <li><a href="/cdn-cgi/l/email-protection#e48e859d8a81a4978196818a8d909dca8687ca968186"><img src="https://i.vimeocdn.com/portrait/9243868_600x600.jpg">Ana Espinar</a></li>
               
              </div>
            </section>
          </div>
        </div>
     
         
     
     
         
     
     
        <div class="large-3 columns">
          <h5>Map</h5>
           
          <p>
            <a href="" data-reveal-id="mapModal"><img src="http://gestioncultura.cervantes.es/COMUNES/31560_I_ceu.jpg"></a><br/>
            <a href="" data-reveal-id="mapModal">View Map</a>
          </p>
          <p>
            Calle Julián Romea, <br/>
            18, 28003 Madrid
          </p>
        </div>
         
      </div>
     
       
     
     
       
     
<%= render 'layouts/footer_contact'%>
       
     
     
     
       
     
      <div class="reveal-modal" id="mapModal">
        <h4>Where We Are</h4>
        <p><img src="http://placehold.it/800x600"/></p>
     
         
        <a href="#" class="close-reveal-modal">×</a>
      </div>
    





 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/musics.html.erb
    <!DOCTYPE html>
<html>
<head>
 <meta name="viewport" content="width=device-width, initial-scale=1.0" />
 <title>Todo</title>
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'vendor/modernizr', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>

 <%= render 'layouts/nav_contact'%>
</head>
<body>

      <div class="row">
        <div class="large-12 columns">
     
         
          <div class="row">
            <div class="large-12 columns">
     
               
            </div>
          </div>
     
          <div class="row">
                        <div class="large-4 small-12 columns">
     
              <img src="https://pbs.twimg.com/profile_images/471913312972963840/QtyDx1mi.jpeg">
     
              <div class="hide-for-small panel">
                <h3>Header</h3>
                <h5 class="subheader">Risus ligula, aliquam nec fermentum vitae, sollicitudin eget urna. Donec dignissim nibh fermentum odio ornare sagittis.
                </h5>
              </div>
     
              <a href="#">
       
              </a>
     
            </div>
            
               <%= yield %>
          </div>
          <%= render 'layouts/footer_contact'%>
     
        </div>
      </div>

 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/photos.html.erb
      
      <!DOCTYPE html>
<html>
<head>
 <meta name="viewport" content="width=device-width, initial-scale=1.0" />
 <title>Todo</title>
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'vendor/modernizr', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>

 <%= render 'layouts/nav_contact'%>
</head>
<body>

  <%= yield %>

    
     
     
     
      <div class="row">
        <div class="large-12 columns">
        <div id="slider">
          <img src="http://placehold.it/1000x400&text=[ img 1 ]"/>
        </div>
        
        <hr/>
        </div>
      </div>
      

     
     
      <div class="row">
        <div class="large-4 columns">
          <img src="http://placehold.it/400x300&text=[img]"/>
          <h4>This is a content section.</h4>
          <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
        </div>
        
        <div class="large-4 columns">
          <img src="http://placehold.it/400x300&text=[img]"/>
          <h4>This is a content section.</h4>
          <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
        </div>
        
        <div class="large-4 columns">
          <img src="http://placehold.it/400x300&text=[img]"/>
          <h4>This is a content section.</h4>
          <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
        </div>
      
        </div>
        
     
    <div class="row">
        <div class="large-12 columns">
        
          <div class="panel">
            <h4>Get in touch!</h4>
                
            <div class="row">
              <div class="large-9 columns">
                <p>We'd love to hear from you, you attractive person you.</p>
              </div>
              <div class="large-3 columns">
                <a href="#" class="radius button right">Contact Us</a>
              </div>
            </div>
          </div>
          

          
        </div>
      </div>
     
     <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>   
      
      <%= render 'layouts/footer_contact'%>

</html>
    

app/views/musics/_form.html.erb
<%= form_for(@music) do |f| %>
  <% if @music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% @music.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musics/edit.html.erb
<h1>Editing music</h1>

<%= render 'form' %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<%= link_to 'New Music', new_music_path %>


     
         
     
     
         
     
            <div class="large-8 columns">
              <div class="row">
         <% @musics.each do |music| %>
            <div class="large-4 small-6 columns">
                  <img src="http://placehold.it/1000x1000&text=Thumbnail">
     
                  <div class="panel">
                    <h5><%= music.title %></h5>
                    <h6 class="subheader"><%= link_to 'Show', music %>
        <%= link_to 'Edit', edit_music_path(music) %>
        <%= link_to 'Destroy', music, method: :delete, data: { confirm: 'Are you sure?' } %></h6>
                  </div>
                </div>     
    <% end %>


    
              </div>
     
         
     
     
         
              <div class="row">
                <div class="large-12 columns">
                  <div class="panel">
                    <div class="row">
     
                      <div class="large-2 small-6 columns">
                        <img src="http://placehold.it/300x300&text=Site Owner">
                      </div>
     
                      <div class="large-10 small-6 columns">
                        <strong>This Site Is Managed By<hr/></strong>
     
                        Risus ligula, aliquam nec fermentum vitae, sollicitudin eget urna. Donec dignissim nibh fermentum odio ornare sagittis
                      </div>
     
                    </div>
                  </div>
                </div>
     
         
     
              </div>
            </div>

app/views/musics/new.html.erb
<h1>New music</h1>

<%= render 'form' %>

<%= link_to 'Back', musics_path %>

app/views/musics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @music.title %>
</p>

<%= link_to 'Edit', edit_music_path(@music) %> |
<%= link_to 'Back', musics_path %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <thead>
    <tr>
      <th>Blanca</th>
      <th>Concerts</th>
      <th>Fans</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.Blanca %></td>
        <td><%= photo.concerts %></td>
        <td><%= photo.fans %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Blanca:</strong>
  <%= @photo.Blanca %>
</p>

<p>
  <strong>Concerts:</strong>
  <%= @photo.concerts %>
</p>

<p>
  <strong>Fans:</strong>
  <%= @photo.fans %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>